### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by mdenni23** [madeline-bauer/frontend-web-dev#43]
doesn't work

**Comment by tcjdesign** [comment]
Has this been fixed @mdenni23? Or is it just fixed for you?

**Comment by tcjdesign** [comment]
I still can't run. Get err:


```
PS C:\Users\tcj\Documents\2017 - College Semester 7\Web-Based Application Design\Computing in Community Website\frontend-web-dev> npm run build

> frontend@1.0.0 build C:\Users\tcj\Documents\2017 - College Semester 7\Web-Based Application Design\Computing in Community Website\frontend-web-dev
> node build/build.js

module.js:538
    throw err;
    ^

Error: Cannot find module 'chalk'

    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\tcj\Documents\2017 - College Semester 7\Web-Based Application Design\Computing in Community Website\frontend-web
-dev\build\check-versions.js:1:75)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tcj\AppData\Roaming\npm-cache\_logs\2017-12-11T17_27_50_143Z-debug.log
```

npm log has:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle frontend@1.0.0~predev: frontend@1.0.0
6 silly lifecycle frontend@1.0.0~predev: no script for predev, continuing
7 info lifecycle frontend@1.0.0~dev: frontend@1.0.0
8 verbose lifecycle frontend@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle frontend@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\tcj\Documents\2017 - College Semester 7\Web-Based Application Design\Computing in Community Website\frontend-web-dev\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Program Files\Process Lasso\;C:\Program Files\Git\cmd;C:\Users\tcj\AppData\Local\Microsoft\WindowsApps;C:\Users\tcj\AppData\Roaming\npm
10 verbose lifecycle frontend@1.0.0~dev: CWD: C:\Users\tcj\Documents\2017 - College Semester 7\Web-Based Application Design\Computing in Community Website\frontend-web-dev
11 silly lifecycle frontend@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle frontend@1.0.0~dev: Returned: code: 3221225786  signal: null
13 info lifecycle frontend@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: frontend@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 3221225786
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid frontend@1.0.0
16 verbose cwd C:\Users\tcj\Documents\2017 - College Semester 7\Web-Based Application Design\Computing in Community Website\frontend-web-dev
17 error Windows_NT 10.0.16299
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.11.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error frontend@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 3221225786
23 error Failed at the frontend@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the frontend package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs frontend
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls frontend
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by tcjdesign** [comment]
This seems to be mostly fixed. I still get errors from uglifyjs, but I get usable build files.
